// Generated by CoffeeScript 1.8.0
(function() {
  var InquiryListView;

  InquiryListView = Ember.ListView.extend({
    height: 500,
    rowHeight: 400,
    itemViewClass: Ember.ListItemView.extend({
      templateName: "inquiry_row_item"
    })
  });

  module.exports = InquiryListView;

}).call(this);
