// Generated by CoffeeScript 1.8.0
(function() {
  var App;

  require('../vendor/jquery');

  require('../vendor/handlebars');

  require('../vendor/ember');

  require('../vendor/ember-data');

  require('../vendor/list-view-latest');

  require('../vendor/bootstrap.min');

  App = Ember.Application.create();

  App.Store = require('./store');

  module.exports = App;

}).call(this);
