// Generated by CoffeeScript 1.8.0
(function() {
  var App;

  App = require('./app');

  App.Router.map(function() {
    this.route('inquiry');
    this.route('listings');
    this.route('sellers');
    return this.route('results');
  });

}).call(this);
