// Generated by CoffeeScript 1.8.0
(function() {
  require('../vendor/localstorage_adapter');

  module.exports = DS.Store.extend({
    revision: 11,
    adapter: DS.LSAdapter.create()
  });

}).call(this);
