// Generated by CoffeeScript 1.8.0
(function() {
  var IndexRoute;

  IndexRoute = Ember.Route.extend({
    beforeModel: function() {
      return this.transitionTo("inquiry");
    }
  });

  module.exports = IndexRoute;

}).call(this);
