// Generated by CoffeeScript 1.8.0
(function() {
  var ListingsRoute, ResultsRoute, utils;

  utils = require('../utils/utils');

  ResultsRoute = require('./results_route');

  ListingsRoute = ResultsRoute.extend();

  module.exports = ListingsRoute;

}).call(this);
