// Generated by CoffeeScript 1.8.0
(function() {
  var SellersRoute, utils;

  utils = require('../utils/utils');

  SellersRoute = Ember.Route.extend({
    model: function() {
      return utils.get_url('http://' + utils.BACKEND_URL + '/manufacturer_list').then(function(succ_ret) {
        var parsedResult;
        parsedResult = $.parseJSON(succ_ret);
        debugger;
        return {
          sellerNames: parsedResult
        };
      }, function(fail_ret) {
        return console.log('FAILURE IN SELLERS_ROUTE');
      });
    }
  });

  module.exports = SellersRoute;

}).call(this);
