// Generated by CoffeeScript 1.8.0
(function() {
  var utils;

  utils = {
    get_url: function(url) {
      return new Promise(function(resolve, reject) {
        var req;
        req = new XMLHttpRequest();
        req.open('GET', url);
        req.onload = function() {
          if (req.status === 200) {
            return resolve(req.response);
          } else {
            return reject(Error(req.statusText));
          }
        };
        req.onerror = function() {
          return reject(Error("Network Error"));
        };
        return req.send();
      });
    },
    upload_data_promise: function(url, data) {
      console.log(data);
      console.log(JSON.stringify(data));
      return $.ajax({
        url: url,
        data: {
          json_str: JSON.stringify(data)
        },
        dataType: 'text',
        type: 'post',
        async: true
      });
    },
    determine_price: function(batteryType, minPrices, price, discountPercent) {
      var batteryLimit;
      batteryLimit = minPrices[batteryType] === '' ? 0 : Number(minPrices[batteryType]);
      price = price * (1 - discountPercent / 100);
      return Math.max(batteryLimit, price);
    },
    BACKEND_URL: "amazon-repricer-backend.herokuapp.com"
  };

  module.exports = utils;

}).call(this);
